version: "3.8"

services:
  db:
    image: andrewtwoosnam/psql-iron-steel-plants
    ports:
      - "5432:5432"
    env_file:
      - .env

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env

  test:
    build:
      dockerfile: Dockerfile.test
    depends_on:
      - app
    env_file:
      - .env
    command: pytest tests/
    profiles: [test]
