version: "3.8"

services:
  db:
    container_name: postgres-db
    image: andrewtwoosnam/psql-iron-steel-plants:latest
    ports:
      - "5432:5432"
    env_file:
      - .env

  flask-api:
    container_name: flask-api
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "5000:5000"

  test:
    build:
      dockerfile: Dockerfile.test
    depends_on:
      - flask-api
    env_file:
      - .env
    command: pytest tests/
    profiles: [test]
