version: "3.8"

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env

  test:
    build:
      dockerfile: Dockerfile.test
    depends_on:
      - app
    env_file:
      - .env
    command: pytest tests/
    profiles: [test]

volumes:
  pgdata:
